project_id = "uzdtqomtbrccinrkhzme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost" # This is for local dev, ensure it's correct for your setup

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173" # For local dev, your React app's URL

[storage]
enabled = true

[analytics]
enabled = true
port = 54327

# [experimental] # Section can be removed if empty, or if 'multiservice' was the only key
# multiservice = true # REMOVE THIS LINE

# Corrected functions configuration
[functions.chat]
verify_jwt = true # Assuming you want to verify JWT for this function

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.list-vector-store-files]
verify_jwt = true

[functions.process-syllabus]
verify_jwt = true # Or false if it doesn't need user context beyond what's passed

[functions.upload-to-vector-store]
verify_jwt = true # Or false if it's a more general utility not tied to a specific user session for the call itself

[functions.delete-openai-resources]
verify_jwt = true # Or false, depending on how you want to secure it.
                  # True is safer if called from an authenticated client context.

# Add your new function here
[functions.provision-class-resources]
# verify_jwt = true # If called by an authenticated client
# verify_jwt = false # If it's a more backend process or uses service_role for all its auth needs internally
# For the provision-class-resources function, since it's called by the client after a user action
# and uses a service_role key internally for DB updates, setting verify_jwt = true is reasonable
# to ensure only authenticated users can trigger it. The --no-verify-jwt flag on deploy
# is separate and affects how Supabase itself handles the function's invocation permissions at the gateway.
# Let's assume true for now, as it's generally safer for client-invoked functions.
verify_jwt = true
