project_id = "uzdtqomtbrccinrkhzme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost" # This is for local dev, ensure it's correct for your setup

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:8080" # Ensure this matches your Vite dev port (was 5173, changed to 8080 based on vite.config.ts)
# If your Vite dev server is on 5173, use that. If it's 8080 (as per vite.config.ts), use 8080.

[storage]
enabled = true

[analytics]
enabled = true
port = 54327

# Functions configuration
[functions.chat]
verify_jwt = true 

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.list-vector-store-files]
verify_jwt = true

[functions.process-syllabus]
verify_jwt = true 

[functions.upload-to-vector-store]
verify_jwt = true 

[functions.delete-openai-resources]
verify_jwt = true 

[functions.web-chat]
verify_jwt = true 

[functions.provision-class-resources]
verify_jwt = true

# ** ADDED NEW FUNCTION CONFIGURATION **
[functions.delete-user-account]
verify_jwt = true # Important: This function should only be callable by an authenticated user
