
project_id = "uzdtqomtbrccinrkhzme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[storage]
enabled = true

[analytics]
enabled = true
port = 54327

[experimental]
multiservice = true

[[functions]]
name = "chat"
verify_jwt = true

[[functions]]
name = "generate-flashcards"
verify_jwt = true

[[functions]]
name = "generate-quiz"
verify_jwt = true

[[functions]]
name = "process-syllabus"
verify_jwt = true

[[functions]]
name = "list-vector-store-files"
verify_jwt = true

[[functions]]
name = "upload-to-vector-store"
verify_jwt = true
