
project_id = "uzdtqomtbrccinrkhzme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[inbucket]
enabled = true

[functions]
[functions.generate-flashcards]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true
