# supabase/config.toml
project_id = "uzdtqomtbrccinrkhzme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost" # This is for local dev, ensure it's correct for your setup

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:8080"

[storage]
enabled = true

[analytics]
enabled = true
port = 54327

# Functions configuration

# Removed: [functions.generate-flashcards]
# Removed: verify_jwt = true

# Removed: [functions.generate-quiz]
# Removed: verify_jwt = true

[functions.upload-to-vector-store]
verify_jwt = true 

[functions.check-env-vars]
verify_jwt = true

[functions.generate-title]
verify_jwt = true

[functions.generate-previews]
verify_jwt = true

[functions.request-previews]
verify_jwt = true

[functions.oracle-chat]
verify_jwt = true

[functions.debug-weaviate-chunks]
verify_jwt = true

[functions.serve-file]
verify_jwt = true

[functions.semantic-search]
verify_jwt = true

[functions.delete-from-cloudinary]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.delete-weaviate-chunks-by-file]
verify_jwt = true