
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzdtqomtbrccinrkhzme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZHRxb210YnJjY2lucmtoem1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzY5MTIsImV4cCI6MjA2MjI1MjkxMn0.Fh8z-GRcM84tBoiSSeFE21Vhqho9rUfgC8e0jiZMOl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    }
  }
);
