// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbldoxurkcpbtdswcbkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibGRveHVya2NwYnRkc3djYmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzEwNTksImV4cCI6MjA2MjE0NzA1OX0.X0uiklItEZgkrtMSqKWUGCAzzlJv831E-BgHIBncoko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);